#!/bin/bash

##############################################################################
#                                                                            #
#  Color definitions from related config files are generated by              #
#  Pywal templates and merged with the commands below into a single          #
#  configrc file again. To do this, the original configrc file              #
#  (cleaned from color definitions generated by Pywal templates)             #
#  must be renamed manually to config.conf.                                  #
#                                                                            #
##############################################################################


# Dynamic color formatting for module clock calendar view

# Path to Waybar file
waybar_file="$HOME/.config/waybar/dcol_modules/clock.json"

# Path to replacement file
replacement_file="$HOME/.cache/wal/module-clock.dcol"

# Check whether replacement file exists
if [ -f "$replacement_file" ]; then
    # Replace sections in Waybar file
    awk -v replacement_file="$replacement_file" '
      BEGIN {
        # Read replacement file into an array
        while ((getline < replacement_file) > 0) {
          replacement_array[++num_replacements] = $0
        }
        close(replacement_file)
      }

      # Replace "months" section
      /"months":/,/"/ {
        if (!replaced_months) {
          print replacement_array[1]
          replaced_months = 1
          next
        }
      }

      # Replace "weekdays" section
      /"weekdays":/,/"/ {
        if (!replaced_weekdays) {
          print replacement_array[2]
          replaced_weekdays = 1
          next
        }
      }

      # Replace "today" section
      /"today":/,/"/ {
        if (!replaced_today) {
          print replacement_array[3]
          replaced_today = 1
          next
        }
      }

      # Output all remaining lines by default
      {
        print
      }
    ' "$waybar_file" > tmpfile && mv tmpfile "$waybar_file"

    echo "Replacement completed successfully."
else
    echo "Error: Replacement file does not exist."
fi
