#############
### INPUT ###
#############
# Docs: https://man.archlinux.org/man/sway-input.5

input type:keyboard xkb_layout "us,ua"
input type:keyboard xkb_options "grp:alt_shift_toggle"

input type:pointer accel_profile "flat"
input type:pointer pointer_accel 0

input type:touchpad natural_scroll disabled
input type:touchpad tap enabled
