################
### MONITORS ###
################
# Docs: https://man.archlinux.org/man/sway-output.5

output DP-3     resolution 1920x1080@75Hz position 0    0
output HDMI-A-1 resolution 1920x1080@75Hz position 1920 0
