#################
### VARIABLES ###
#################

set $terminal    kitty
set $fileManager thunar
set $menu        b1air-shell toggle launcher

# Xwayland support for legacy X11 apps (AnyDesk, Steam, Discord screenshare)
xwayland enable
