#################
### VARIABLES ###
#################

set $terminal    kitty
set $fileManager nautilus
set $menu        qs -p $HOME/.config/quickshell/Main.qml ipc call main toggleLauncher
set $menu_rofi   rofi -show drun
