[config]
version_check = false

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-colors.json"
output_path = "/tmp/qs_colors.json"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/matugen-colors.conf"

[templates.cava]
input_path = "~/.config/matugen/templates/cava-colors.ini"
output_path = "~/.config/cava/colors"

[templates.nvim]
input_path = "~/.config/matugen/templates/nvim-colors.lua"
output_path = "~/.config/nvim/lua/matugen-colors.lua"

[templates.sddm]
input_path = "~/.config/matugen/templates/sddm-colors.conf"
output_path = "~/.cache/matugen/sddm-colors.conf"
