#!/bin/bash

##############################################################################
#                                                                            #
#  Color definitions from the related config files are generated by Pywal     #
#  templates and then merged into a single configrc file using the commands   #
#  below. For this to work, the original configrc file (cleaned of color      #
#  definitions generated by Pywal templates) must be manually renamed         #
#  to config.conf.                                                            #
#                                                                            #
##############################################################################


#Jgmenu
cat "$HOME/.config/jgmenu/jgmenurc.conf" "$HOME/.cache/wal/colors-jgmenu.conf" > "$HOME/.config/jgmenu/jgmenurc" &
