#!/bin/bash

##############################################################################
#                                                                            #
#  Color definitions from related config files are generated by              #
#  Pywal templates and merged with the commands below into a single          #
#  configrc file again. To do this, the original configrc file              #
#  (cleaned from color definitions generated by Pywal templates)             #
#  must be renamed manually to config.conf.                                  #
#                                                                            #
##############################################################################


# SDDM
cat "/usr/share/sddm/themes/corners/themerc.conf" "$HOME/.cache/wal/colors-sddm.conf" > "/usr/share/sddm/themes/corners/theme.conf" &
