#!/usr/bin/env bash
set -euo pipefail

img_path="${1:-}"
contrast_file="$HOME/.config/waybar/contrast.css"

mkdir -p "$(dirname "$contrast_file")"

brightness_pct=45

if [[ -n "$img_path" && -f "$img_path" ]]; then
    if command -v magick >/dev/null 2>&1; then
        brightness_pct="$(magick "$img_path[0]" -colorspace Gray -resize 1x1 -format "%[fx:int(mean*100)]" info: 2>/dev/null || echo 45)"
    elif command -v convert >/dev/null 2>&1; then
        brightness_pct="$(convert "$img_path[0]" -colorspace Gray -resize 1x1 -format "%[fx:int(mean*100)]" info: 2>/dev/null || echo 45)"
    fi
fi

if [[ "$brightness_pct" =~ ^[0-9]+$ ]] && (( brightness_pct >= 58 )); then
    text_color="rgba(244, 247, 255, 0.98)"
    dim_color="rgba(224, 230, 248, 0.90)"
    panel_bg="rgba(9, 11, 18, 0.94)"
    panel_bg_alt="rgba(11, 14, 22, 0.92)"
    border_color="rgba(255, 255, 255, 0.34)"
    hover_bg="rgba(136, 186, 255, 0.26)"
    active_bg="rgba(122, 162, 247, 0.88)"
else
    text_color="rgba(236, 242, 255, 0.96)"
    dim_color="rgba(195, 206, 233, 0.86)"
    panel_bg="rgba(18, 22, 34, 0.88)"
    panel_bg_alt="rgba(15, 18, 28, 0.84)"
    border_color="rgba(152, 188, 255, 0.30)"
    hover_bg="rgba(136, 186, 255, 0.22)"
    active_bg="rgba(122, 162, 247, 0.78)"
fi

cat > "$contrast_file" <<EOF
/* Auto-generated by generate_waybar_contrast.sh */
window#waybar {
  color: ${text_color} !important;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.70) !important;
}

tooltip {
  background: ${panel_bg} !important;
  color: ${text_color} !important;
  border: 1px solid ${border_color} !important;
  box-shadow: 0 8px 22px rgba(0, 0, 0, 0.55) !important;
}

#quicklinks, #workspaces, #taskbar, #misc, #devices, #system, #custom-appmenu {
  background: ${panel_bg_alt} !important;
  border-top: 1px solid ${border_color} !important;
  border-bottom: 1px solid ${border_color} !important;
}

#workspaces button, #taskbar button {
  color: ${dim_color} !important;
  border: 1px solid rgba(255, 255, 255, 0.12) !important;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.70) !important;
}

#workspaces button:hover, #taskbar button:hover {
  background: ${hover_bg} !important;
  border-color: ${border_color} !important;
}

#workspaces button.active, #taskbar button.active {
  background: ${active_bg} !important;
  color: rgba(14, 18, 30, 0.98) !important;
  border: 1px solid rgba(220, 236, 255, 0.75) !important;
  box-shadow: 0 0 12px rgba(122, 162, 247, 0.45) !important;
}

#bluetooth, #pulseaudio, #wireplumber, #network {
  color: ${dim_color} !important;
}
EOF
