background {
    monitor =
    path =                  
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(20, 20, 30, 0.85)
    font_color = rgba(220, 220, 220, 1.0)
    fade_on_empty = true
    placeholder_text = <i>Enter password...</i>
    dots_spacing = 0.3
    dots_center = true
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 72
    font_family = Fira Sans SemiBold
    color = rgba(220, 220, 220, 0.9)
    position = 0, 200
    halign = center
    valign = center
}